### ISSUE TITLE
Consider alternative implementations

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-sentry#10]
At least the following implementations are possible:

1. Current one.
2. As a logger target. Logging is triggered by error handler so we have fatals and out of memory in sentry.

We need to consider second one because having fatals and out of memory errors in Sentry is a big win.

**Comment by samdark** [comment]
Logger target could be added later.

**Comment by arogachev** [comment]
@samdark Just in case, is this still actual? And you mean addition, not replacement, right?

**Comment by samdark** [comment]
Yes and yes.

**Comment by arogachev** [comment]
Did some testing and dug deeper into Sentry docs and seems like current Sentry SDK (in pair with PHP 8) already handles it for us. For more details see this section - https://docs.sentry.io/platforms/php/integrations/.
